package com.jhftyyyty.githubuploader

internal class AppStrings(val ar: Boolean) {
    val app = "GitHub uploader"
    val subtitle = if (ar) "إدارة مشاريع GitHub من الهاتف" else "Manage GitHub projects from your phone"

    val token = if (ar) "رمز GitHub" else "GitHub token"
    val show = if (ar) "إظهار" else "Show"
    val hide = if (ar) "إخفاء" else "Hide"
    val createToken = if (ar) "إنشاء رمز" else "Create token"

    val operation = if (ar) "العملية" else "Operation"
    val newRepo = if (ar) "مستودع جديد" else "New repository"
    val download = if (ar) "تنزيل" else "Download"

    val repoName = if (ar) "اسم المستودع" else "Repository name"
    val description = if (ar) "الوصف" else "Description"
    val privateRepo = if (ar) "خاص" else "Private"
    val publicRepo = if (ar) "عام" else "Public"
    val repository = if (ar) "المستودع" else "Repository"
    val chooseRepo = if (ar) "اختر المستودع" else "Choose repository"
    val refreshRepositories = if (ar) "تحديث قائمة المستودعات" else "Refresh repositories"
    val noRepositories = if (ar) "حدّث القائمة لاختيار مستودع" else "Refresh to choose a repository"

    val source = if (ar) "مصدر المشروع" else "Project source"
    val chooseZip = if (ar) "اختيار ZIP" else "Choose ZIP"
    val noFile = if (ar) "لم يتم اختيار ملف" else "No file selected"
    val start = if (ar) "بدء العملية" else "Start"
    val working = if (ar) "جارٍ التنفيذ…" else "Working…"
    val cancel = if (ar) "إلغاء العملية" else "Cancel operation"
    val resuming = if (ar) "يتم استئناف الرفع تلقائيًا عند عودة الاتصال" else "Upload resumes automatically when the connection returns"
    val done = if (ar) "تمت العملية بنجاح" else "Operation completed"
    val downloadDone = if (ar) "تم تنزيل المشروع بنجاح" else "Project downloaded successfully"
    val cancelled = if (ar) "تم إلغاء العملية" else "Operation cancelled"
    val error = if (ar) "حدث خطأ" else "Something went wrong"
    val result = if (ar) "تم إنشاء رابط المستودع" else "Repository link is ready"
    val openOnGitHub = if (ar) "فتح المستودع على GitHub" else "Open repository on GitHub"
    val savedToDownloads = if (ar) "تم حفظ الملف" else "File saved"
    val downloadFolder = if (ar) "Download/GitHubUploader" else "Download/GitHubUploader"
    val openFile = if (ar) "فتح" else "Open"
    val openZip = if (ar) "تعذر قراءة ملف ZIP" else "Could not read ZIP"

    val settings = if (ar) "الإعدادات" else "Settings"
    val help = if (ar) "المساعدة" else "Help"
    val back = if (ar) "رجوع" else "Back"
    val theme = if (ar) "المظهر" else "Appearance"
    val system = if (ar) "تلقائي" else "System"
    val light = if (ar) "فاتح" else "Light"
    val amoled = "AMOLED"
    val language = if (ar) "اللغة" else "Language"
    val autoNaming = if (ar) "تسمية المستودع تلقائيًا" else "Auto-name repository"
    val autoNamingSub = if (ar) "استخدم اسم ملف ZIP كاسم المستودع عند إنشاء مستودع جديد." else "Use the ZIP filename as the repository name for new repositories."
    val projectLink = if (ar) "مشروع GitHub uploader" else "GitHub uploader project"
    val openProject = if (ar) "فتح صفحة المشروع على GitHub" else "Open the project on GitHub"
    val refreshHint = if (ar) "اضغط تحديث قائمة المستودعات لتحميل مستودعات حسابك." else "Refresh repositories to load the repositories in your account."
    val arabic = if (ar) "العربية" else "Arabic"
    val english = if (ar) "الإنجليزية" else "English"
    val notConnected = if (ar) "غير متصل" else "Not connected"
    val authHint = if (ar) "استخدم رمز GitHub للوصول إلى حسابك." else "Use a GitHub token to access your account."

    val help1 = if (ar) "إنشاء الرمز: افتح Developer settings ثم Personal access tokens > Fine-grained tokens واختر Generate new token." else "Create a token: open Developer settings, then Personal access tokens > Fine-grained tokens, and choose Generate new token."
    val help2 = if (ar) "صلاحيات الرفع: Contents = Read and write وMetadata = Read-only. لإنشاء مستودعات جديدة استخدم Administration = Read and write. وأضف Workflows = Read and write إذا كان التطبيق سيعدل ملفات GitHub Actions." else "Upload permissions: Contents = Read and write and Metadata = Read-only. For new repositories use Administration = Read and write. Add Workflows = Read and write if the app will modify GitHub Actions files."
    val help3 = if (ar) "حدد المستودعات التي يحتاج إليها الرمز فقط، ثم انسخه والصقه في التطبيق. لا تشاركه مع أي شخص ويمكنك إلغاؤه من GitHub." else "Limit the token to the repositories it needs, then paste it into the app. Never share it; you can revoke it from GitHub."
    val help4 = if (ar) "الرفع الذكي يقارن Git SHA مع الملفات الموجودة على GitHub، لذلك الملفات التي لم تتغير لا تُرفع مرة أخرى." else "Smart upload compares Git SHAs with GitHub, so unchanged files are not uploaded again."
    val help5 = if (ar) "إذا انقطع الإنترنت، يحتفظ التطبيق بملف ZIP ويعيد المحاولة تلقائيًا عند عودة الاتصال، ويستفيد من الملفات التي تم رفعها بالفعل." else "If the connection drops, the app keeps the ZIP and retries automatically when the connection returns, reusing blobs already uploaded."
    val help6 = if (ar) "يمكنك إلغاء العملية في أي وقت. عند الإلغاء يتوقف الرفع ويحذف ملف الرفع المؤقت." else "You can cancel at any time. Cancelling stops the upload and removes its temporary upload file."
    val help7 = if (ar) "مصدر الرفع هو ZIP فقط. ويمكنك إرسال ملف ZIP إلى التطبيق مباشرةً من قائمة المشاركة في مدير الملفات." else "ZIP is the only upload source. You can send a ZIP directly to the app from your file manager share menu."
    val help8 = if (ar) "الملفات المتغيرة تُرفع بالتوازي لتسريع المشاريع الكبيرة، مع معالجة ZIP على دفعات لتقليل استهلاك الذاكرة." else "Changed files are uploaded in parallel for better speed on large projects, while the ZIP is processed in bounded batches to reduce memory use."
    val help9 = if (ar) "التسمية التلقائية تستخدم اسم ملف ZIP كاسم المستودع الجديد، ويمكن تشغيلها أو إيقافها من الإعدادات." else "Auto-naming uses the ZIP filename as the new repository name and can be enabled or disabled in Settings."
    val help10 = if (ar) "التنزيل يحفظ نسخة ZIP من فرع المستودع المحدد." else "Download saves a ZIP copy of the selected repository branch."
}
