package com.jhftyyyty.githubuploader
internal class AppStrings(val ar:Boolean){
val app="GitHub uploader";val subtitle=if(ar)"رفع وتنزيل ومزامنة مشاريع GitHub من الهاتف" else "Upload, download and sync GitHub projects"
val token=if(ar)"رمز GitHub" else "GitHub token";val show=if(ar)"إظهار" else "Show";val hide=if(ar)"إخفاء" else "Hide"
val browserLogin=if(ar)"تسجيل الدخول بالمتصفح" else "Sign in with browser";val browserLoginHint=if(ar)"افتح GitHub في المتصفح وأدخل الكود الظاهر." else "Open GitHub in your browser and enter the code."
val enterCode=if(ar)"الكود" else "Code";val openBrowser=if(ar)"فتح المتصفح" else "Open browser";val connect=if(ar)"بدء الربط" else "Start";val check=if(ar)"تحقق" else "Check";val waiting=if(ar)"في انتظار GitHub…" else "Waiting for GitHub…";val cancel=if(ar)"إلغاء" else "Cancel";val createToken=if(ar)"إنشاء توكن" else "Create token"
val operation=if(ar)"العملية" else "Operation";val newRepo=if(ar)"مستودع جديد" else "New repository";val updateRepo=if(ar)"تحديث" else "Update";val download=if(ar)"تنزيل" else "Download";val syncMode=if(ar)"مزامنة كاملة" else "Exact sync";val syncHint=if(ar)"يحذف من GitHub الملفات التي لم تعد موجودة في ZIP." else "Deletes remote files that are no longer in the ZIP."
val repoName=if(ar)"اسم المستودع" else "Repository name";val description=if(ar)"الوصف" else "Description";val privateRepo=if(ar)"خاص" else "Private";val publicRepo=if(ar)"عام" else "Public";val repository=if(ar)"المستودع" else "Repository";val chooseRepo=if(ar)"اختر المستودع" else "Choose repository";val refresh=if(ar)"تحديث" else "Refresh"
val source=if(ar)"مصدر المشروع" else "Project source";val chooseZip=if(ar)"اختيار ZIP" else "Choose ZIP";val noFile=if(ar)"لم يتم اختيار ملف" else "No file selected";val start=if(ar)"بدء العملية" else "Start";val working=if(ar)"جارٍ التنفيذ…" else "Working…";val done=if(ar)"اكتملت العملية" else "Completed";val cancelled=if(ar)"تم الإلغاء" else "Cancelled";val error=if(ar)"حدث خطأ" else "Error";val result=if(ar)"النتيجة" else "Result";val openZip=if(ar)"تعذر قراءة ملف ZIP" else "Could not read ZIP"
val settings=if(ar)"الإعدادات" else "Settings";val help=if(ar)"المساعدة" else "Help";val back=if(ar)"رجوع" else "Back";val appearance=if(ar)"المظهر" else "Appearance";val theme=if(ar)"المظهر" else "Theme";val system=if(ar)"تلقائي" else "System";val light=if(ar)"فاتح" else "Light";val amoled="AMOLED";val language=if(ar)"اللغة" else "Language";val arabic=if(ar)"العربية" else "Arabic";val english=if(ar)"الإنجليزية" else "English";val security=if(ar)"الأمان" else "Security"
val securityHint=if(ar)"التوكن يُخزّن مشفّرًا باستخدام Android Keystore." else "Tokens are encrypted with Android Keystore.";val notConnected=if(ar)"غير متصل" else "Not connected";val authHint=if(ar)"استخدم التوكن أو تسجيل الدخول بالمتصفح." else "Use a token or browser sign-in."
val help1=if(ar)"اختر ZIP ثم أنشئ مستودعًا أو حدّث مستودعًا موجودًا." else "Choose a ZIP, then create or update a repository.";val help2=if(ar)"التحديث يرفع الملفات المتغيرة فقط، بينما المزامنة الكاملة تطابق GitHub مع ZIP." else "Update uploads changed files; Exact sync mirrors the ZIP.";val help3=if(ar)"التنزيل يحفظ نسخة ZIP من فرع المستودع الحالي." else "Download saves the selected repository branch as a ZIP.";val help4=if(ar)"الملفات الكبيرة تُعالج على دفعات لتقليل استهلاك الذاكرة." else "Large files are processed in bounded chunks.";val help5=if(ar)"يمكنك استخدام Fine-grained Token بصلاحية Contents للرفع والتحديث." else "A Fine-grained Token with Contents access can be used."
}