package com.jhftyyyty.githubuploader

internal class AppStrings(val ar: Boolean) {
    val app = "GitHub uploader"
    val subtitle = if (ar) "إدارة مشاريع GitHub من الهاتف" else "Manage GitHub projects from your phone"

    val token = if (ar) "رمز GitHub" else "GitHub token"
    val show = if (ar) "إظهار" else "Show"
    val hide = if (ar) "إخفاء" else "Hide"
    val browserLogin = if (ar) "تسجيل الدخول بالمتصفح" else "Sign in with browser"
    val browserLoginHint = if (ar) "افتح GitHub في المتصفح وأكمل تسجيل الدخول." else "Open GitHub in your browser to continue."
    val enterCode = if (ar) "الكود" else "Code"
    val openBrowser = if (ar) "فتح المتصفح" else "Open browser"
    val connect = if (ar) "بدء الربط" else "Connect"
    val check = if (ar) "تحقق" else "Check"
    val waiting = if (ar) "في انتظار GitHub…" else "Waiting for GitHub…"
    val cancel = if (ar) "إلغاء" else "Cancel"
    val createToken = if (ar) "إنشاء رمز" else "Create token"

    val operation = if (ar) "العملية" else "Operation"
    val newRepo = if (ar) "مستودع جديد" else "New repository"
    val updateRepo = if (ar) "تحديث" else "Update"
    val download = if (ar) "تنزيل" else "Download"
    val syncMode = if (ar) "مزامنة كاملة" else "Exact sync"
    val syncHint = if (ar) "يطابق محتوى GitHub مع ملف ZIP ويحذف الملفات الزائدة." else "Mirrors the ZIP and removes remote files not in it."

    val repoName = if (ar) "اسم المستودع" else "Repository name"
    val description = if (ar) "الوصف" else "Description"
    val privateRepo = if (ar) "خاص" else "Private"
    val publicRepo = if (ar) "عام" else "Public"
    val repository = if (ar) "المستودع" else "Repository"
    val chooseRepo = if (ar) "اختر المستودع" else "Choose repository"
    val refreshRepositories = if (ar) "تحديث قائمة المستودعات" else "Refresh repositories"
    val noRepositories = if (ar) "حدّث القائمة لاختيار مستودع" else "Refresh to choose a repository"

    val source = if (ar) "مصدر المشروع" else "Project source"
    val chooseZip = if (ar) "اختيار ZIP" else "Choose ZIP"
    val noFile = if (ar) "لم يتم اختيار ملف" else "No file selected"
    val start = if (ar) "بدء العملية" else "Start"
    val working = if (ar) "جارٍ التنفيذ…" else "Working…"
    val done = if (ar) "تمت العملية بنجاح" else "Operation completed"
    val downloadDone = if (ar) "تم تنزيل المشروع بنجاح" else "Project downloaded successfully"
    val cancelled = if (ar) "تم إلغاء العملية" else "Operation cancelled"
    val error = if (ar) "حدث خطأ" else "Something went wrong"
    val result = if (ar) "تم إنشاء رابط المستودع" else "Repository link is ready"
    val openOnGitHub = if (ar) "فتح المستودع على GitHub" else "Open repository on GitHub"
    val savedToDownloads = if (ar) "تم حفظ الملف" else "File saved"
    val downloadFolder = if (ar) "Download/GitHubUploader" else "Download/GitHubUploader"
    val openFile = if (ar) "فتح" else "Open"
    val openZip = if (ar) "تعذر قراءة ملف ZIP" else "Could not read ZIP"

    val settings = if (ar) "الإعدادات" else "Settings"
    val help = if (ar) "المساعدة" else "Help"
    val back = if (ar) "رجوع" else "Back"
    val theme = if (ar) "المظهر" else "Appearance"
    val system = if (ar) "تلقائي" else "System"
    val light = if (ar) "فاتح" else "Light"
    val amoled = "AMOLED"
    val language = if (ar) "اللغة" else "Language"
    val arabic = if (ar) "العربية" else "Arabic"
    val english = if (ar) "الإنجليزية" else "English"
    val notConnected = if (ar) "غير متصل" else "Not connected"
    val authHint = if (ar) "استخدم رمزًا أو سجّل الدخول بالمتصفح." else "Use a token or sign in with your browser."

    val help1 = if (ar) "إنشاء رمز GitHub: افتح صفحة Developer settings ثم Personal access tokens > Fine-grained tokens واضغط Generate new token." else "Create a GitHub token: open Developer settings, then Personal access tokens > Fine-grained tokens, and choose Generate new token."
    val help2 = if (ar) "اختر اسمًا للرمز، وحدد مدة الصلاحية المناسبة، ثم اختر الحساب أو المؤسسة التي سيعمل عليها الرمز." else "Give the token a name, choose an expiration period, then select the account or organization it will access."
    val help3 = if (ar) "لرفع وتحديث الملفات: من Repository permissions فعّل Contents = Read and write، واترك Metadata = Read-only." else "For upload and update: set Repository permissions → Contents = Read and write, and Metadata = Read-only."
    val help4 = if (ar) "لإنشاء مستودع جديد أيضًا: فعّل Repository creation أو Administration = Read and write إذا ظهر هذا الخيار في حسابك." else "To create new repositories too: enable Repository creation or Administration = Read and write when offered for your account."
    val help5 = if (ar) "بعد إنشاء الرمز انسخه مرة واحدة والصقه داخل التطبيق. لا تشاركه مع أي شخص، ويمكنك إلغاؤه من GitHub في أي وقت." else "Copy the token once and paste it into the app. Never share it; you can revoke it from GitHub at any time."
    val help6 = if (ar) "إذا كنت تستخدم تسجيل الدخول بالمتصفح، لن تحتاج إلى إدخال الرمز يدويًا. أما Fine-grained Token فهو الأفضل عند الحاجة لتحديد المستودعات والصلاحيات." else "Browser sign-in can be used without manually entering a token. Fine-grained Tokens are preferable when you want scoped repositories and permissions."
    val help7 = if (ar) "التحديث يرفع الملفات المتغيرة فقط، بينما المزامنة الكاملة تطابق محتوى GitHub مع ملف ZIP وتحذف الملفات التي لم تعد موجودة." else "Update uploads changed files only, while Exact sync mirrors the ZIP and removes files no longer present."
    val help8 = if (ar) "التنزيل يحفظ نسخة ZIP من فرع المستودع المحدد." else "Download saves a ZIP copy of the selected repository branch."
    val help9 = if (ar) "الملفات الكبيرة تُعالج على دفعات لتقليل استهلاك الذاكرة." else "Large files are processed in bounded chunks."
}
